= Installation
We'll use microk8s as our k8s environment. It works nicely on Linux,
has its own registry and is pretty easy to set up.

== Install + configure microk8s
sudo snap install microk8s --classic
alias mkctl="microk8s kubectl"

=== Configure extensions
microk8s enable registry dns dashboard
 
= Setup example app
We'll use Tomcat with a "hello world" webapp for getting started.

= Build + test image locally
== Build Docker image
cd app
docker build -t k8s-playground/tomcat8 .

== Test image in Docker
docker container run -it -d --name tomcatcontainer1 -p 8082:8080 k8s-playground/tomcat8
open http://localhost:8082/SampleWebApp/


= Build + test image in k8s

== Tag + push image to registry
The microk8s registry is running locally on port 32000. Let's build our image:

docker build . -t localhost:32000/mytomcat8webapp:registry
docker push localhost:32000/mytomcat8webapp:registry

== Create a deployment


== Create a deployment

microk8s kubectl apply -f deployment.yaml

=== Check status
microk8s kubectl get all --all-namespaces

==== Check pods
microk8s kubectl get pods -l app=mytomcat8webapp-deployment

=== Get summary
microk8s kubectl describe deployments mytomcat8webapp

=== Scale
microk8s kubectl scale deployment mytomcat8webapp-deployment --replicas=3

== Expose + Connect
microk8s kubectl expose deployment mytomcat8webapp-deployment --port=80 --target-port=8080 --type LoadBalancer

Find out the IP address of your pods:
microk8s kubectl describe svc

Open one of the Endpoints in your browser, e.g. 10.1.0.19:8080 
Et voilà - you've got a running webapp in K8s!

= TODO
* configure ingress for exposing app

